### ISSUE TITLE
Automatic extras on nested inlines causes field is required error

### ISSUE THREAD

**Issue by aiudirog** [theatlantic/django-nested-admin#34]
After playing around a bit, I noticed that if I create a top level inline and it has nested inlines, if the nested inlines have an extras value > 0, the extra inlines that are automatically there won't save the first time. All of their fields will be cleared and the "Field Is Required" error will show for all of the fields that are required on those extra inlines.

I was able to work around this by simply setting each inline to use have 0 extras and then just using the "add <inline>" buttons to add more. If my explanation wasn't clear enough, I can post a video of what is happening.

**Comment by aiudirog** [comment]
I gave that a try and it doesn't seem to work.  Just to make sure we're on the same page, here's a video of what's gong on:

https://www.dropbox.com/s/5seazk2akjwm9ld/Screencast_03-10-2016_05%3A40%3A14%20PM.webm?dl=0

I'm going to take to see if there are any differences in the way the "Add <inline>" button creates new inlines vs how they are auto-generated.

Thank you for your time and help.

**Comment by aiudirog** [comment]
So removing changing [line 591 in nesting.utils.js](https://github.com/theatlantic/django-nested-admin/blob/master/nested_admin/static/nesting/nesting.utils.js#L591) from `newVal = beforeEmpty + index + afterEmpty.replace(index, '__prefix__');` to `newVal = beforeEmpty + index + afterEmpty;` solves the issue for me, however I'm sure that `.replace()` was in there for a reason, so I'm sure there is a more creative solution to only replace the index in some cases instead of a blanket replace.

**Comment by fdintino** [comment]
Thank you for the video, that's very helpful! I'll look into this.

**Comment by aiudirog** [comment]
I've been debugging with PyCharm and really digging though the code to find where the error crops up.  I found where the fields get validated and I know what the real issue is, just not how it got there.  You probably know most of what I have found so far, but for anyone else with this issue I'll post the full explanation. The POST data eventually gets put into a MultiValueDict for each inline. When the field is validated, it goes in and checks the dict for it's particular field id. Since it uses data.get(key), only the last value is pulled off.  For the top most inline, there is only one value in its list, so that loads fine. For the next nested inline, the data list has two values.  The first is the string that was in the field, and the next is blank for some reason.  The blank one is what is read and validated, and now I'm looking into why the blank one is in there.

**Comment by aiudirog** [comment]
I did it! The code looks like crap, but I have a hack that solves the problem.  Basically the issue was that when replacing the index with `__prefix__`, every element was being replaced, even elements one sub level down that were extras.  Basically, the fix was to only modify elements that were not in a template (so whose 'great-grandfather' didn't have an id ending in `-empty`) and were not extras.  

I'm sure that there is a cleaner way the code can be written, however I have spent way to long on this issue so I'm just going to commit the changes to my fork so you can see them.

**Comment by fdintino** [comment]
Wow, thanks so much for your hard work! You are absolutely right about where the problem lies: it's overly greedy about replacing `__prefix__`, and it causes a bug when dealing with nesting 3+ deep. It makes sense also why it wouldn't be caught by our unit tests, which mostly tests two-deep nesting. I'm working on building a unit test for this bug now, and then will commit a fix.

**Comment by aiudirog** [comment]
It was no problem, your version of nested inlines is the only one that works for my project, which is taking this website: http://www.jazzhistorydatabase.com/ that my school hosts and rebuilding it from the ground up, so I didn't have an issue putting time into getting this to work right.

I'm actually looking forward to seeing your tests because as I said before, I honestly don't know how to do effective testing, which is something I really need to write if I'm going to leave my project to someone else someday.

**Comment by fdintino** [comment]
So, in the process of working through a fix, and writing more unit tests for 3+ deep nesting, I discovered that the bug you encountered is actually fairly serious, and affects a lot of functionality. So I think it would be prudent to get out the fix now while I'm still increasing the test coverage. I've pushed out my fix onto the branch [fix-3-plus-deep-nesting](https://github.com/theatlantic/django-nested-admin/compare/fix-3-plus-deep-nesting). Could you quickly verify that this fixes your issue before I merge it into master.

Thanks again! And I'm glad that this project has been helpful to you.

**Comment by aiudirog** [comment]
I will pull down the code in a virtualenv and run it later tonight. Thank you for being open to my other pull request which made me feel welcome to help.:)

**Comment by aiudirog** [comment]
You code seems to work, testing it actually helped me find a few flaws in my own code as I tried to break yours.  Good job, it looks much better than my hack.

**Comment by dacodekid** [comment]
@fdintino / @aiudirog  as soon as I enable sorting option with `sortable_field_name = 'position'`, I'm still getting this issue.  Am I missing something?

```py
class LineItemInline(nested_admin.NestedTabularInline):
    model = LineItem
    form = LineItemForm
    autocomplete_fields = ('part_number',)
    extra = 5
    sortable_field_name = 'position'
    # sortable_excludes = ('position',)  # this isn't working either
```


![image](https://user-images.githubusercontent.com/10047844/34028668-a3e9dafe-e132-11e7-8bf1-65832fa93ee4.png)

**Comment by fdintino** [comment]
@dacodekid are there any hidden fields other than position that have default values? Those are the fields you would want to add to `sortable_excludes`. [This is the relevant code](https://github.com/theatlantic/django-nested-admin/blob/3a75b938ca0b802c180df822d2cdc5e58b321aa1/nested_admin/static/nested_admin/src/nested-admin/sortable.js#L59-L86) that checks whether the inlines have values.

It's also possible that you have discovered a bug. Here are the relevant bits of the tests that check that this functionality is working; perhaps comparing it with your code will provide some clues:

- Test model definition: [nested_admin/tests/two_deep/models.py:92-99](https://github.com/theatlantic/django-nested-admin/blob/3a75b938ca0b802c180df822d2cdc5e58b321aa1/nested_admin/tests/two_deep/models.py#L92-L99)
- Test admin definition:  [nested_admin/tests/two_deep/admin.py:49-54](https://github.com/theatlantic/django-nested-admin/blob/3a75b938ca0b802c180df822d2cdc5e58b321aa1/nested_admin/tests/two_deep/admin.py#L49-L54)
- Test case: [nested_admin/tests/two_deep/tests.py:812-851](https://github.com/theatlantic/django-nested-admin/blob/3a75b938ca0b802c180df822d2cdc5e58b321aa1/nested_admin/tests/two_deep/tests.py#L812-L851)

**Comment by dacodekid** [comment]
Plz never mind. I overlooked what `sortable_excludes` does (and completely missed that I've a column with `default` value.  After read [this part of the code](https://github.com/theatlantic/django-nested-admin/blob/1dba49177e32f2fddd35f191cc836bd88114ac49/nested_admin/static/nested_admin/src/nested-admin/sortable.js#L63), realized my error.  Changed the above commented line to

```py
sortable_excludes = ('unit_price',)
```
fixed the issue.  

However if the `position` field setup to have default value, it breaks.  Adding `position` field to `sortable_excludes` disables the sorting operations.
